start: statement+

statement: expr
    | assign
    | function_definition
    | return_statement

expr: expr "+" term -> add
    | expr "-" term -> sub
    | term

term: term "*" factor -> mul
    | term "/" factor -> div
    | factor

factor: NUMBER -> num
    | "(" expr ")"
    | "-" factor -> neg
    | IDENTIFIER -> var

assign: IDENTIFIER "=" expr -> assign

COMMENT: /\/\/[^\n]*/

code_block: "{" statement+ "}"

function_definition: IDENTIFIER "()" code_block -> function_definition

RETURN_KEYWORD: "return"
return_statement: RETURN_KEYWORD expr

IDENTIFIER: LETTER (LETTER | DIGIT)*

%import common.NUMBER
%import common.LETTER
%import common.DIGIT
%import common.WS
%ignore WS
%ignore COMMENT