start: expr

expr: expr "+" term -> add
    | expr "-" term -> sub
    | term

term: term "*" factor -> mul
    | term "/" factor -> div
    | factor

factor: NUMBER -> num
       | "(" expr ")"
       | "-" factor -> neg
       | assign

assign: IDENTIFIER "=" expr -> assign

IDENTIFIER: LETTER (LETTER | DIGIT)*

%import common.NUMBER
%import common.LETTER
%import common.DIGIT
%import common.WS
%ignore WS